languageCode = "de-de"
DefaultContentLanguage = "de-de"
title = "safeMarket"
themesDir = "themes"
theme = "hugo-hero-theme"

[languages]
  [languages.de-de]
    baseUrl = "de-de"
    title = "SafeMarket"
    weight = 0
  [languages.en]
    baseUrl = "en"
    title = "SafeMarket"
    weight = 1

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "safeMarket - Zuhause Schlange stehen"
    meta_og_title = "safeMarket"
    meta_og_type = "website"
    meta_og_url = "https://aaronkessler.de"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "safeMarket - Zuhause Schlange stehen"
    meta_twitter_card = "summary"
    meta_twitter_site = "@jstask82"
    meta_twitter_creator = "@jstask82"

[permalinks]
  post = ":year/:month/:day/:slug/"
  pages = "/:filename/"