languageCode = "de-de"
DefaultContentLanguage = "de-de"
title = "safeMarket"
themesDir = "themes"
theme = "hugo-hero-theme"

[languages]
  [languages.de-de]
    baseUrl = "/"
    title = "SafeMarket"
    weight = 0
  [languages.en]
    baseUrl = "en"
    title = "SafeMarket"
    weight = 1
    [languages.en.params]
      linkedin = "https://linkedin.com/whoever"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "safeMarket - Zuhause Schlange stehen"
    meta_og_title = "safeMarket"
    meta_og_type = "website"
    meta_og_url = "https://aaronkessler.de"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "safeMarket - Zuhause Schlange stehen"
    meta_twitter_card = "summary"
    meta_twitter_site = "@jstask82"
    meta_twitter_creator = "@jstask82"

[[languages.de-de.menu.main]]
	name = "Vorteile"
	url = "/vorteile/"
    weight = 1

[[languages.de-de.menu.main]]
    name = "Partner"
    url = "/partner/"
    weight = 2

[[languages.de-de.menu.main]]
    name = "Über #wirvsvirus"
    url = "/ueber/"
    weight = 3

[[languages.de-de.menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 4

[[languages.en.menu.main]]
	name = "Advantages"
	url = "/advantages/"
    weight = 1

[[languages.en.menu.main]]
    name = "Partners"
    url = "/partner/"
    weight = 2

[[languages.en.menu.main]]
    name = "About #wirvsvirus"
    url = "/ueber/"
    weight = 3

[[languages.en.menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = ":year/:month/:day/:slug/"
  pages = "/:filename/"